version: '3'
services:
  app:
    build: .
    image: tima011104/first-bank-backend:latest
    ports:
      - "3000:3000"
    networks:
      - app_network
    environment:
      NODE_ENV: production
      POSTGRES_HOST: db
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_NAME: mydatabase
      POSTGRES_DB: mydatabase
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      GEMIMI_API_KEY: AIzaSyBd2NEg5OWzVeMfFHTTGJ7ol0Xc0zrLFvM
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network


volumes:
  pgdata:
    driver: local

networks:
  app_network:
    driver: bridge
