version: '3'
services:
  app:
    build: .
    image: tima011104/first-bank-backend:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      POSTGRES_HOST: localhost
      DB_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_NAME: mydatabase
      POSTGRES_DB: mydatabase
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    driver: local
